### PR TITLE
Added event for initialization

### PR DESCRIPTION
**Pull request by benkoller**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by benkoller** [comment]
[ch2066]

**Comment by benkoller** [comment]
[ch2066]

**Review by htahir1 — COMMENTED** [review]
Nice! I think that solves it. Perhaps we could also edit the `docs/book/misc/usage-analytics.md` to reflect this change? Other than that, should be set to merge

**Comment by benkoller** [comment]
> Nice! I think that solves it. Perhaps we could also edit the `docs/book/misc/usage-analytics.md` to reflect this change? Other than that, should be set to merge

Good idea, added the missing event.

**Pull request merged**
